### ISSUE TITLE
Only supports d6

### ISSUE THREAD

**Issue by rnelson** [ebsen/dice#1]
Perhaps it should support [others](https://en.wikipedia.org/wiki/Dice#Standard_variations)?

**Comment by ebsen** [comment]
Oh, the perils of open source...

I have been asked to support more than one _die_ as well so it looks like I need to design a Settings pane.

**Comment by ebsen** [comment]
Dice now supports any number of faces beyond six, knowing full well that a meatspace (plasticspace?) die may or may not be capable of in fact truly having that number of faces.
